# Generated by Django 2.2.6 on 2019-10-09 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200)),
                ('tresc', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=200)),
                ('nazwisko', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^[0-9]{9}$', 'Numer musi zawierac 9 cyfr')])),
                ('usluga', models.CharField(choices=[('og', 'Odwiedziny grobu'), ('sg', 'Sprzątanie grobu'), ('mn', 'Mycie nagrobka')], max_length=100)),
                ('rodzaj_grobu', models.CharField(choices=[('poj', 'Pojedyńczy'), ('pdw', 'Podwójny'), ('grb', 'Grobowiec')], max_length=100)),
                ('czestotliwosc', models.CharField(choices=[('1', 'Raz w roku'), ('3', 'Trzy razy w roku'), ('6', 'Sześć razy w roku'), ('12', 'Dwanaście razy w roku')], max_length=100)),
                ('komentarz', models.TextField()),
            ],
        ),
    ]
