# Generated by Django 2.2.6 on 2019-10-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191011_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowienie',
            name='data_uslugi',
            field=models.DateField(),
        ),
    ]
