# Generated by Django 2.2.6 on 2019-10-11 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191011_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zamowienie',
            old_name='czestotliwosc',
            new_name='częstotliwość',
        ),
        migrations.RenameField(
            model_name='zamowienie',
            old_name='data_uslugi',
            new_name='data_usługi',
        ),
        migrations.RenameField(
            model_name='zamowienie',
            old_name='imie',
            new_name='imię',
        ),
        migrations.RenameField(
            model_name='zamowienie',
            old_name='imie_zmarłego',
            new_name='imię_zmarłego',
        ),
        migrations.RenameField(
            model_name='zamowienie',
            old_name='usluga',
            new_name='usługa',
        ),
    ]
