# Generated by Django 2.2.6 on 2019-10-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191011_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowienie',
            name='data_urodzenia',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='data_śmierci',
            field=models.DateField(null=True),
        ),
    ]
