# Generated by Django 2.2.6 on 2019-10-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191011_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowienie',
            name='kwatera',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='nr_grobu',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='rząd',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
