# Generated by Django 2.2.6 on 2019-10-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191018_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowienie',
            name='data_urodzenia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='data_usługi',
            field=models.DateField(blank=True, null=True),
        ),
    ]
